<%@ Page Title="Author" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Author.aspx.cs" Inherits="Yenetch.Web.AuthorPage" %>
<%@ MasterType VirtualPath="~/Site.Master" %>
<%@ Import Namespace="System.Linq" %>
<%@ Import Namespace="Yenetch.Data" %>
<%-- Hand-written (not generated by tools/build.py): a blog author's profile at /blog/author/{slug}. --%>
<asp:Content ContentPlaceHolderID="MainContent" runat="server">
<section class="phero"><div class="wrap wrap--text">
  <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a><i>/</i><a href="/blog">Insights</a><i>/</i><span aria-current="page"><%: A.Name %></span></nav>
  <div class="author-hero">
    <%= A.IsTeam && !A.HasPhoto ? "<img class=\"author-card__photo author-mark\" src=\"/assets/img/logo-mark.png\" alt=\"\" width=\"120\" height=\"120\">" : Authors.PhotoHtml(A, "author-card__photo") %>
    <div><span class="kicker"><%: A.IsTeam ? "Authors" : "Author" %></span>
      <h1><%: A.Name %></h1>
      <% if (!string.IsNullOrEmpty(A.Role)) { %><p class="phero__lead" style="margin-top:6px"><%: A.Role %></p><% } %>
      <div class="author-links">
        <% if (!string.IsNullOrEmpty(A.Linkedin)) { %><a class="more" href="<%: A.Linkedin %>" target="_blank" rel="noopener me">LinkedIn</a><% } %>
        <% if (!string.IsNullOrEmpty(A.Twitter)) { %><a class="more" href="<%: A.Twitter %>" target="_blank" rel="noopener me">X (Twitter)</a><% } %>
        <% if (!string.IsNullOrEmpty(A.Website)) { %><a class="more" href="<%: A.Website %>" target="_blank" rel="noopener me">Website</a><% } %>
      </div>
    </div>
  </div>
</div></section>
<section class="sec--tight" style="padding-top:0"><div class="wrap wrap--text">
  <div class="prose">
    <p><b><%: A.Bio %></b></p>
    <% foreach (var p in A.About ?? new System.Collections.Generic.List<string>()) { %><p><%: p %></p><% } %>
  </div>
  <% if (A.Expertise != null && A.Expertise.Count > 0) { %><div class="author-topics" aria-label="Topics"><% foreach (var t in A.Expertise) { %><span><%: t %></span><% } %></div><% } %>
</div></section>
<section class="sec"><div class="wrap">
  <div class="head"><span class="kicker">Articles</span><h2><%= Posts.Count == 0 ? "No articles yet." : "Written by " + Server.HtmlEncode(A.Name.Split(' ')[0]) + "." %></h2></div>
  <div class="posts posts--grid">
  <% foreach (var p in Posts) { %>
    <a class="post" href="<%: p.Url %>"><figure class="post__cover"><img src="<%: Photos.Src(p.CoverImage) %>" alt="" loading="lazy" decoding="async" /></figure>
      <div class="post__body"><div class="post__meta"><b><%: p.Category %></b><span><%= p.ReadMinutes %> min read</span></div><h3><%: p.Title %></h3><p><%: p.Excerpt %></p><time datetime="<%: p.Date %>"><%: p.DisplayDate %></time></div></a>
  <% } %>
  </div>
</div></section>
<script type="application/ld+json"><%= Ld %></script>
</asp:Content>
