//------------------------------------------------------------------------------
// <auto-generated>
//     Author.aspx has no server controls.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web
{
    public partial class AuthorPage
    {
        public new global::Yenetch.Web.SiteMaster Master { get { return ((global::Yenetch.Web.SiteMaster)(base.Master)); } }
    }
}
