<%@ Page Title="Insights | Marketing, Software &amp; Growth Guides | Yenetch" MetaDescription="Practical guides on digital marketing, SEO, software, e-commerce and hiring from the Yenetch team." Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Blog.aspx.cs" Inherits="Yenetch.Web.Blog" %>
<%@ MasterType VirtualPath="~/Site.Master" %>
<%@ Import Namespace="Yenetch.Data" %>
<%-- Generated by tools/build.py from tools/sitegen/pages.py. Edit the template and re-run the build. --%>
<asp:Content ContentPlaceHolderID="MainContent" runat="server">

<section class="phero"><div class="wrap">
  <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a><i>/</i><span aria-current="page">Insights</span></nav>
  <span class="kicker">Insights</span>
  <h1><span class="ln"><span>Field notes from</span></span><span class="ln"><span>people doing the <span class="blue">work.</span></span></span></h1>
  <p class="phero__lead">Practical guides on marketing, software, e-commerce and hiring, written by the specialists who run these projects every day.</p>
  <div class="chips-filter" aria-label="Categories"><a class="chip<%= string.IsNullOrEmpty(Category) ? " is-on" : "" %>" href="/blog">All</a><asp:Repeater runat="server" ItemType="System.String" DataSource='<%# Categories %>'><ItemTemplate><a class="chip" href="/blog/category/<%#: Yenetch.Models.BlogPost.Slugify(Item) %>"><%#: Item %></a></ItemTemplate></asp:Repeater></div>
</div></section>
<section class="sec--tight" style="padding-top:0"><div class="wrap">
  <asp:PlaceHolder runat="server" Visible='<%# Featured != null %>'><a class="feature fx-up" href="<%: Featured.Url %>"><figure><img src="<%: Photos.Src(Featured.CoverImage) %>" srcset="<%: Photos.SrcSet(Featured.CoverImage) %>" sizes="(max-width: 900px) 100vw, 60vw" alt="<%: Photos.Alt(Featured.CoverImage) %>" fetchpriority="high"></figure>
  <div class="feature__body"><div class="post__meta"><b><%: Featured.Category %></b><span><%: Featured.ReadMinutes %> min read</span></div><h2><%: Featured.Title %></h2><p><%: Featured.Excerpt %></p><time datetime="<%: Featured.Date %>"><%: Featured.DisplayDate %></time><span class="more">Read article</span></div></a></asp:PlaceHolder>
  <div class="posts posts--grid fx-stagger"><asp:Repeater runat="server" ItemType="Yenetch.Models.BlogPost" DataSource='<%# Posts %>'><ItemTemplate><a class="post" href="<%#: Item.Url %>"><figure class="post__cover"><img src="<%#: Photos.Src(Item.CoverImage) %>" srcset="<%#: Photos.SrcSet(Item.CoverImage) %>" sizes="(max-width: 900px) 100vw, 33vw" alt="<%#: Photos.Alt(Item.CoverImage) %>" loading="lazy" decoding="async"></figure>
  <div class="post__body"><div class="post__meta"><b><%#: Item.Category %></b><span><%#: Item.ReadMinutes %> min read</span></div><h3><%#: Item.Title %></h3><p><%#: Item.Excerpt %></p><time datetime="<%#: Item.Date %>"><%#: Item.DisplayDate %></time></div></a></ItemTemplate></asp:Repeater></div>
  <%= PagerHtml %>
</div></section>
<section class="sec--tight"><div class="wrap"><div class="news fx-up">
  <div><span class="kicker">Newsletter</span><h2>One useful note a month.</h2><p>Marketing and software ideas you can use, never spam. Unsubscribe any time.</p></div>
  <form class="news__form" data-newsletter><label class="sr-only" for="news-email">Email</label><input id="news-email" class="field" type="email" required placeholder="you@company.com" autocomplete="email"><button class="btn btn--blue" type="submit">Subscribe</button></form>
</div></div></section>

</asp:Content>
