<%@ Page Title="Book a Free Consultation Call | Yenetch" MetaDescription="Pick a time for a free 30-minute call with a Yenetch specialist in marketing, software or hiring. Confirmation and calendar invite by email." Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Book.aspx.cs" Inherits="Yenetch.Web.Book" %>
<%@ MasterType VirtualPath="~/Site.Master" %>
<%@ Import Namespace="Yenetch.Data" %>
<%-- Generated by tools/build.py from tools/sitegen/pages.py. Edit the template and re-run the build. --%>
<asp:Content ContentPlaceHolderID="MainContent" runat="server">

<section class="phero"><div class="wrap">
  <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a><i>/</i><span aria-current="page">Book a call</span></nav>
  <span class="kicker">Book a call</span>
  <h1 class="bk__title"><%: Yenetch.Crm.Bookings.Config.Heading %></h1>
  <p class="phero__lead"><%: Yenetch.Crm.Bookings.Config.Intro %></p>
</div></section>
<section class="sec--tight" style="padding-top:0"><div class="wrap contact">
  <div class="contact__form bk" data-book>
    <div class="bk__step" data-bk-step="day">
      <div class="bk__label"><b>1</b><span>Pick a day</span><small data-bk-tz></small></div>
      <div class="bk__days" data-bk-days role="listbox" aria-label="Available days"><p class="bk__loading">Loading open times…</p></div>
    </div>
    <div class="bk__step" data-bk-step="time" hidden>
      <div class="bk__label"><b>2</b><span>Pick a time</span><small data-bk-dayname></small></div>
      <div class="bk__times" data-bk-times role="listbox" aria-label="Available times"></div>
    </div>
    <form class="cform bk__form" data-bk-form hidden novalidate>
      <div class="bk__label"><b>3</b><span>Your details</span><small data-bk-chosen></small></div>
      <div class="bk__grid">
        <div class="cform__row"><label for="bk-name">Your name *</label><input class="field" id="bk-name" name="name" required maxlength="120" autocomplete="name"></div>
        <div class="cform__row"><label for="bk-email">Email *</label><input class="field" id="bk-email" name="email" type="email" required maxlength="160" autocomplete="email"></div>
        <div class="cform__row"><label for="bk-phone">Phone *</label><input class="field" id="bk-phone" name="phone" type="tel" required maxlength="40" autocomplete="tel"></div>
        <div class="cform__row"><label for="bk-company">Company</label><input class="field" id="bk-company" name="company" maxlength="160" autocomplete="organization"></div>
      </div>
      <div class="cform__row"><label for="bk-topic">What would you like to discuss?</label><select class="field" id="bk-topic" name="topic" data-bk-topics></select></div>
      <fieldset class="cform__row bk__modes"><legend>How should we talk?</legend><div data-bk-modes></div></fieldset>
      <div class="cform__row"><label for="bk-notes">Anything we should prepare? (optional)</label><textarea class="field" id="bk-notes" name="notes" rows="3" maxlength="2000"></textarea></div>
      <input type="text" name="website" tabindex="-1" autocomplete="off" aria-hidden="true" style="position:absolute;left:-9999px">
      <div data-captcha></div>
      <p class="apl__error" role="alert" hidden data-bk-error></p>
      <div class="bk__actions"><button class="btn btn--blue" type="submit">Confirm booking</button><button class="btn btn--line" type="button" data-bk-back>Change time</button></div>
      <p class="cform__note">You'll get a confirmation email with a calendar invite. We use your details only for this call. See our <a href="/privacy">privacy policy</a>.</p>
    </form>
    <div class="cform__done" data-bk-done hidden><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m5 12 5 5 9-10"/></svg><h2>You're booked.</h2><p data-bk-done-text>We've emailed you the details and a calendar invite.</p><a class="btn btn--line" href="/">Back to the website</a></div>
    <div class="bk__closed" data-bk-closed hidden><h2>Online booking is closed right now.</h2><p>Call or WhatsApp us and we'll find a time.</p></div>
  </div>
  <aside class="contact__side">
    <div class="ccard ccard--social"><small>What to expect</small>
      <ul class="bk__expect"><li><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m5 12 5 5 9-10"/></svg>A specialist in your area, not a salesperson</li><li><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m5 12 5 5 9-10"/></svg>A clear next step, whatever you decide</li><li><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m5 12 5 5 9-10"/></svg>Free, with no obligation</li></ul></div>
    <a class="ccard" href="<%: Yenetch.Data.Site.PhoneTel %>"><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 4h4l2 5-2.5 1.5a11 11 0 0 0 5 5L15 13l5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2"/></svg><span><small>Prefer to talk now?</small><b><%: Yenetch.Data.Site.Company.Phone %></b></span></a>
    <a class="ccard" href="<%: Yenetch.Data.Site.WhatsApp("Hi Yenetch, I'd like to book a call.") %>" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z"/></svg><span><small>WhatsApp</small><b>Chat with us</b></span></a>
  </aside>
</div></section>

</asp:Content>
