//------------------------------------------------------------------------------
// <auto-generated>
//     Hand-written page without server controls. Kept for Visual Studio.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web
{
    public partial class BookCancel
    {
        /// <summary>Master property (typed by the MasterType directive).</summary>
        public new global::Yenetch.Web.SiteMaster Master
        {
            get { return ((global::Yenetch.Web.SiteMaster)(base.Master)); }
        }
    }
}
