//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/build.py. Changes to this file will be lost when the build runs again.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web
{
    public partial class Contact
    {
        /// <summary>FormFields control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder FormFields;

        /// <summary>Name control.</summary>
        protected global::System.Web.UI.WebControls.TextBox Name;

        /// <summary>ContactInfo control.</summary>
        protected global::System.Web.UI.WebControls.TextBox ContactInfo;

        /// <summary>Interest control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList Interest;

        /// <summary>Need control.</summary>
        protected global::System.Web.UI.WebControls.TextBox Need;

        /// <summary>Attachment control.</summary>
        protected global::System.Web.UI.WebControls.FileUpload Attachment;

        /// <summary>FormError control.</summary>
        protected global::System.Web.UI.WebControls.Literal FormError;

        /// <summary>SendButton control.</summary>
        protected global::System.Web.UI.WebControls.Button SendButton;

        /// <summary>ThankYou control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder ThankYou;

        /// <summary>Master property (typed by the MasterType directive).</summary>
        public new global::Yenetch.Web.SiteMaster Master
        {
            get { return ((global::Yenetch.Web.SiteMaster)(base.Master)); }
        }
    }
}
