<%@ Page Title="Contact Yenetch | Gurugram &amp; Jaipur | {phone}" MetaDescription="Talk to Yenetch about marketing, software or dedicated teams. Call {phone}, WhatsApp, email {email} or visit our offices." Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Contact.aspx.cs" Inherits="Yenetch.Web.Contact" %>
<%@ MasterType VirtualPath="~/Site.Master" %>
<%@ Import Namespace="Yenetch.Data" %>
<%-- Generated by tools/build.py from tools/sitegen/pages.py. Edit the template and re-run the build. --%>
<asp:Content ContentPlaceHolderID="MainContent" runat="server">

<section class="phero"><div class="wrap">
  <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a><i>/</i><span aria-current="page">Contact</span></nav>
  <span class="kicker">Contact</span>
  <h1><span class="ln"><span>Let's talk about</span></span><span class="ln"><span>your <span class="blue">goals.</span></span></span></h1>
  <p class="phero__lead">Share a few details and a specialist will reply within one working day. Prefer to talk now? We're a call or a WhatsApp away.</p>
</div></section>
<section class="sec--tight" style="padding-top:0"><div class="wrap contact">
  <div class="contact__form"><form id="ContactForm" runat="server" class="cform">
    <asp:PlaceHolder ID="FormFields" runat="server">
      <div class="cform__row"><label for="Name">Your name</label><asp:TextBox ID="Name" runat="server" CssClass="field" MaxLength="120" autocomplete="name" />
      <asp:RequiredFieldValidator runat="server" ControlToValidate="Name" ErrorMessage="Please enter your name." Display="Dynamic" CssClass="err" /></div>
      <div class="cform__row"><label for="ContactInfo">Phone or email</label><asp:TextBox ID="ContactInfo" runat="server" CssClass="field" MaxLength="160" autocomplete="email" />
      <asp:RequiredFieldValidator runat="server" ControlToValidate="ContactInfo" ErrorMessage="Please enter a phone number or email." Display="Dynamic" CssClass="err" /></div>
      <div class="cform__row"><label for="Interest">I'm interested in</label><asp:DropDownList ID="Interest" runat="server" CssClass="field" DataSource='<%# IsPostBack ? null : Yenetch.Data.Site.ContactTopics %>' SelectedValue='<%# IsPostBack ? Interest.SelectedValue : Yenetch.Data.Site.ContactTopic(Request.QueryString["service"]) %>' /></div>
      <div class="cform__row"><label for="Need">What do you want to achieve?</label><asp:TextBox ID="Need" runat="server" CssClass="field" TextMode="MultiLine" Rows="5" MaxLength="1000" /></div>
      <div class="cform__row"><label for="Attachment">Attach a brief (optional)</label><asp:FileUpload ID="Attachment" runat="server" CssClass="field" accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.jpg,.jpeg,.png,.webp,.txt" aria-describedby="AttachmentHint" /><small class="cform__hint" id="AttachmentHint">PDF, Word, Excel, PowerPoint or image, up to 5 MB</small></div>
      <asp:Button ID="SendButton" runat="server" Text="Send enquiry" CssClass="btn btn--blue" OnClick="SendButton_Click" />
      <p class="cform__note">We reply within one working day. Your details are used only to respond to you. See our <a href="/privacy">privacy policy</a>.</p>
    </asp:PlaceHolder>
    <asp:PlaceHolder ID="ThankYou" runat="server" Visible="false"><div class="cform__done"><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m5 12 5 5 9-10"/></svg><h2>Thank you.</h2><p>A specialist will reach you within one working day.</p></div></asp:PlaceHolder>
  </form></div>
  <aside class="contact__side">
    <a class="ccard" href="<%: Yenetch.Data.Site.PhoneTel %>"><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 4h4l2 5-2.5 1.5a11 11 0 0 0 5 5L15 13l5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2"/></svg><span><small>Call</small><b><%: Yenetch.Data.Site.Company.Phone %></b></span></a>
    <a class="ccard" href="<%: Yenetch.Data.Site.WhatsApp("Hi Yenetch") %>" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z"/></svg><span><small>WhatsApp</small><b>Chat with us</b></span></a>
    <a class="ccard" href="<%: Yenetch.Data.Site.MailTo(null) %>"><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></svg><span><small>Email</small><b><%: Yenetch.Data.Site.Company.Email %></b></span></a>
    <a class="ccard" href="/book"><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="4.5" width="18" height="16.5" rx="3"/><path d="M8 2.5v4M16 2.5v4M3 10h18M8 14h2M14 14h2M8 17.5h2"/></svg><span><small>Free 30-minute call</small><b>Book a time</b></span></a>
    <button class="ccard" type="button" data-chat="Talk to an expert"><svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 5h16v11H9l-5 4z"/></svg><span><small>Instant answers</small><b>Ask our assistant</b></span></button>
    <div class="ccard ccard--social"><small>Follow us</small><div class="social"><asp:Repeater runat="server" ItemType="Yenetch.Models.SocialLink" DataSource='<%# Yenetch.Data.Site.Social %>'><ItemTemplate><a href="<%#: Item.Url %>" target="_blank" rel="noopener" aria-label="Yenetch on <%#: Item.Name %>"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="<%#: Yenetch.Data.Site.SocialIconPath(Item.Id) %>"/></svg></a></ItemTemplate></asp:Repeater></div></div>
  </aside>
</div></section>
<section class="sec paper"><div class="wrap">
  <div class="head fx-up"><span class="kicker">Offices</span><h2>Visit us.</h2></div>
  <div class="offices"><asp:Repeater runat="server" ItemType="Yenetch.Models.Office" DataSource='<%# Yenetch.Data.Site.Offices %>'><ItemTemplate><article class="office office--sm"><figure><img src="<%#: Photos.Src(Item.Photo) %>" srcset="<%#: Photos.SrcSet(Item.Photo) %>" sizes="(max-width: 800px) 100vw, 30vw" alt="<%#: Photos.Alt(Item.Photo) %>" loading="lazy" decoding="async"></figure><div><span class="kicker"><%#: Item.Label %></span><h3><%#: Item.City %></h3><p><%#: Item.Address %></p><a class="more" href="<%#: Item.Map %>" target="_blank" rel="noopener">Get directions</a></div></article></ItemTemplate></asp:Repeater></div>
</div></section>
<asp:PlaceHolder runat="server"><%= Yenetch.Crm.Reviews.WidgetHtml() %></asp:PlaceHolder><asp:PlaceHolder runat="server"><script type="application/ld+json"><%= Yenetch.Data.Seo.LocalBusinesses() %></script></asp:PlaceHolder>

</asp:Content>
