//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/build.py. Changes to this file will be lost when the build runs again.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web
{
    public partial class Landing
    {
        /// <summary>Master property (typed by the MasterType directive).</summary>
        public new global::Yenetch.Web.SiteMaster Master
        {
            get { return ((global::Yenetch.Web.SiteMaster)(base.Master)); }
        }
    }
}
