<%@ Page Title="Privacy Policy | Yenetch" MetaDescription="How Yenetch collects, uses and protects personal information shared through yenetch.com." Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Privacy.aspx.cs" Inherits="Yenetch.Web.Privacy" %>
<%@ MasterType VirtualPath="~/Site.Master" %>
<%@ Import Namespace="Yenetch.Data" %>
<%-- Generated by tools/build.py from tools/sitegen/pages.py. Edit the template and re-run the build. --%>
<asp:Content ContentPlaceHolderID="MainContent" runat="server">

<section class="phero"><div class="wrap wrap--text">
  <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a><i>/</i><span aria-current="page">Privacy policy</span></nav>
  <h1><span class="ln"><span>Privacy</span></span><span class="ln"><span>policy.</span></span></h1>
  <p class="phero__lead">Last updated 1 October 2026.</p>
</div></section>
<section class="sec--tight" style="padding-top:0"><div class="wrap wrap--text"><div class="prose"><%= Yenetch.Data.SiteContent.LegalHtml("privacy") %></div></div></section>

</asp:Content>
