//------------------------------------------------------------------------------
// <auto-generated>
//     The proposal page has no server controls.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web
{
    public partial class ProposalPage
    {
    }
}
