<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Proposal.aspx.cs" Inherits="Yenetch.Web.ProposalPage" %>
<%@ Import Namespace="System.Linq" %>
<%@ Import Namespace="Yenetch.Crm" %>
<%-- Hand-written (not generated by tools/build.py): the client's view of a proposal at /proposal/{token}. --%>
<!DOCTYPE html>
<html lang="en-IN">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <meta name="robots" content="noindex, nofollow" />
    <meta name="referrer" content="no-referrer" />
    <title><%: P == null ? "Proposal not found" : P.Number + " · " + P.Title %> | Yenetch</title>
    <link rel="icon" href="/assets/img/favicon.svg" type="image/svg+xml" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@500;600;700&amp;family=Inter:wght@400;500;600&amp;display=swap" />
    <link rel="stylesheet" href="/assets/css/site.css?v=11" />
</head>
<body class="prop-body">
<header class="prop-top"><div class="wrap prop-top__in"><a class="logo" href="/" aria-label="Yenetch home"><img src="/assets/img/logo-mark.png" alt="" width="28" height="28" /><span>yenetch</span></a>
    <% if (P != null) { %><button class="btn btn--line btn--sm" type="button" onclick="window.print()">Download PDF</button><% } %></div></header>
<main class="wrap prop">
<% if (P == null) { %>
    <section class="prop-card"><h1>Proposal not found</h1><p>This link may be mistyped or the proposal may have been withdrawn. Please contact the person who sent it.</p><a class="btn btn--blue" href="/contact">Contact Yenetch</a></section>
<% } else { %>
    <% if (Request.QueryString["paid"] == "1" && P.IsPaid) { %><div class="prop-flash prop-flash--ok" role="status"><b>Payment received.</b> Thank you. A receipt is on its way to your email.</div><% } %>
    <% if (IsStaff) { %><div class="prop-flash" role="status">You are signed in to the admin, so this visit is not counted as a client view. <a href="/admin/proposals/<%= P.Id %>">Edit proposal</a></div><% } %>
    <section class="prop-card prop-head">
        <div><span class="kicker">Proposal <%: P.Number %></span><h1><%: P.Title %></h1>
            <p class="prop-meta">Prepared for <b><%: P.ClientName %></b><%= string.IsNullOrEmpty(P.ClientCompany) ? "" : ", " + H(P.ClientCompany) %> · <%: Util.Date(P.CreatedOn) %><%= P.ValidUntil.HasValue ? " · Valid until " + H(Util.Date(P.ValidUntil)) : "" %></p></div>
        <div class="prop-status"><%= StatusHtml %></div>
    </section>
    <% if (!string.IsNullOrWhiteSpace(P.Intro)) { %><section class="prop-card"><div class="prop-intro"><%= Paragraphs(P.Intro) %></div></section><% } %>
    <section class="prop-card">
        <h2>Scope and investment</h2>
        <div class="prop-table-wrap"><table class="prop-table">
            <thead><tr><th>Item</th><th>Qty</th><th>Price</th><th>Amount</th></tr></thead>
            <tbody><% foreach (var i in P.Items) { %><tr>
                <td><b><%: i.Name %></b><% if (!string.IsNullOrEmpty(i.Description)) { %><span><%: i.Description %></span><% } %></td>
                <td class="nowrap"><%= i.Qty.ToString("0.##") %><%= string.IsNullOrEmpty(i.Unit) ? "" : " " + H(i.Unit) %></td>
                <td class="nowrap"><%: P.Money(i.Price) %><%= Per(i.Billing) %></td>
                <td class="nowrap"><b><%: P.Money(i.Amount) %></b><%= Per(i.Billing) %></td>
            </tr><% } %></tbody>
        </table></div>
        <dl class="prop-totals">
            <% if (P.Monthly > 0 || P.Yearly > 0) { %><div><dt>One-time</dt><dd><%: P.Money(P.OneTime) %></dd></div><% } %>
            <% if (P.Monthly > 0) { %><div><dt>First month</dt><dd><%: P.Money(P.Monthly) %></dd></div><% } %>
            <% if (P.Yearly > 0) { %><div><dt>First year</dt><dd><%: P.Money(P.Yearly) %></dd></div><% } %>
            <% if (P.Discount > 0) { %><div><dt>Discount (<%= P.DiscountPct.ToString("0.##") %>%)</dt><dd>−<%: P.Money(P.Discount) %></dd></div><% } %>
            <% if (P.Tax > 0) { %><div><dt><%: P.TaxName %> (<%= P.TaxPct.ToString("0.##") %>%)</dt><dd><%: P.Money(P.Tax) %></dd></div><% } %>
            <div class="prop-totals__big"><dt>Total first payment</dt><dd><%: P.Money(P.Total) %></dd></div>
            <% if (P.DepositPct > 0 && P.DepositPct < 100) { %><div><dt>Due on acceptance (<%= P.DepositPct.ToString("0.##") %>%)</dt><dd><%: P.Money(P.DueNow) %></dd></div><% } %>
            <% if (P.Monthly > 0) { %><div><dt>Then each month</dt><dd><%: P.Money(P.MonthlyAfter) %></dd></div><% } %>
        </dl>
    </section>
    <% if (!string.IsNullOrWhiteSpace(P.Terms)) { %><section class="prop-card"><h2>Terms</h2><ul class="prop-terms"><% foreach (var t in P.Terms.Split('\n')) { if (t.Trim().Length == 0) continue; %><li><%: t.Trim() %></li><% } %></ul></section><% } %>

    <section class="prop-card prop-act" data-proposal="<%: P.Token %>">
    <% if (P.AcceptedOn.HasValue) { %>
        <h2>Accepted</h2><p>Accepted by <b><%: P.AcceptedName %></b> on <%: Util.When(P.AcceptedOn) %>. Thank you!</p>
        <% if (!P.IsPaid && !string.IsNullOrEmpty(P.PayLinkUrl)) { %><p>Amount due now: <b><%: P.Money(P.PayAmount ?? P.DueNow) %></b></p><a class="btn btn--blue" href="<%: P.PayLinkUrl %>" rel="noopener">Pay securely</a><% } %>
        <% if (P.IsPaid) { %><p><b>Paid:</b> <%: P.Money(P.AmountPaid ?? 0) %> on <%: Util.Date(P.PaidOn) %>.</p><% } %>
        <% if (Portal != null) { %><p class="prop-portal">Track billing, tasks and project progress in your client portal.</p><a class="btn btn--line" href="<%: Portal %>" rel="noopener">Open client portal</a><% } %>
    <% } else if (P.DeclinedOn.HasValue) { %>
        <h2>Declined</h2><p>This proposal was declined on <%: Util.Date(P.DeclinedOn) %>. Changed your mind? <a href="/contact">Get in touch</a> and we'll send an updated one.</p>
    <% } else if (P.IsExpired) { %>
        <h2>This proposal has expired</h2><p>It was valid until <%: Util.Date(P.ValidUntil) %>. <a href="/contact">Contact us</a> for an updated proposal.</p>
    <% } else { %>
        <h2>Accept this proposal</h2>
        <form class="prop-accept" data-accept novalidate>
            <label for="acc-name">Type your full name to sign</label>
            <input class="field" id="acc-name" name="name" maxlength="160" autocomplete="name" required value="<%: P.ClientName %>" />
            <label class="prop-check"><input type="checkbox" name="agree" value="1" required /> I have read the scope, investment and terms above, and I accept this proposal<%= string.IsNullOrEmpty(P.ClientCompany) ? "" : " on behalf of " + H(P.ClientCompany) %>.</label>
            <p class="apl__error" role="alert" hidden data-error></p>
            <div class="prop-btns"><button class="btn btn--blue" type="submit">Accept proposal</button><button class="btn btn--line" type="button" data-decline-open>Decline</button></div>
        </form>
        <form class="prop-decline" data-decline hidden novalidate>
            <label for="dec-reason">Could you tell us why? (optional)</label>
            <textarea class="field" id="dec-reason" name="reason" rows="3" maxlength="1000"></textarea>
            <div class="prop-btns"><button class="btn btn--line" type="submit">Decline proposal</button><button class="btn btn--line" type="button" data-decline-cancel>Back</button></div>
        </form>
        <div class="prop-done" data-done hidden></div>
    <% } %>
    </section>
    <section class="prop-card prop-contact"><p>Questions? Call <a href="<%: Yenetch.Data.Site.PhoneTel %>"><%: Yenetch.Data.Site.Company.Phone %></a> or reply to the email this came with.</p></section>
<% } %>
</main>
<script src="/assets/js/proposal.js?v=11" defer></script>
</body>
</html>
