//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/build.py. Changes to this file will be lost when the build runs again.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web
{
    public partial class SiteMaster
    {    }
}
