<%@ Page Title="Terms of Use | Yenetch" MetaDescription="Terms governing the use of the Yenetch website." Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Terms.aspx.cs" Inherits="Yenetch.Web.Terms" %>
<%@ MasterType VirtualPath="~/Site.Master" %>
<%@ Import Namespace="Yenetch.Data" %>
<%-- Generated by tools/build.py from tools/sitegen/pages.py. Edit the template and re-run the build. --%>
<asp:Content ContentPlaceHolderID="MainContent" runat="server">

<section class="phero"><div class="wrap wrap--text">
  <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a><i>/</i><span aria-current="page">Terms of use</span></nav>
  <h1><span class="ln"><span>Terms of</span></span><span class="ln"><span>use.</span></span></h1>
  <p class="phero__lead">Last updated 1 October 2026.</p>
</div></section>
<section class="sec--tight" style="padding-top:0"><div class="wrap wrap--text"><div class="prose"><%= Yenetch.Data.SiteContent.LegalHtml("terms") %></div></div></section>

</asp:Content>
