//------------------------------------------------------------------------------
// <auto-generated>
//     Designer fields for Unsubscribe.aspx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web
{
    public partial class Unsubscribe
    {
        protected global::System.Web.UI.WebControls.PlaceHolder AskPanel;
        protected global::System.Web.UI.WebControls.Literal EmailText;
        protected global::System.Web.UI.WebControls.Button ConfirmButton;
        protected global::System.Web.UI.WebControls.PlaceHolder DonePanel;
        protected global::System.Web.UI.WebControls.Button ResubscribeButton;
        protected global::System.Web.UI.WebControls.PlaceHolder BackPanel;
        protected global::System.Web.UI.WebControls.PlaceHolder MissingPanel;
        public new global::Yenetch.Web.SiteMaster Master { get { return ((global::Yenetch.Web.SiteMaster)(base.Master)); } }
    }
}
