//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/admin_designers.py from Account.aspx.
//     Changes to this file are lost when it is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web.Admin
{
    public partial class Account
    {
        protected global::System.Web.UI.WebControls.TextBox MyName;

        protected global::System.Web.UI.WebControls.Button NameButton;

        protected global::System.Web.UI.WebControls.TextBox CurrentPassword;

        protected global::System.Web.UI.WebControls.TextBox NewPassword;

        protected global::System.Web.UI.WebControls.TextBox ConfirmPassword;

        protected global::System.Web.UI.WebControls.Button PasswordButton;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
