//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/admin_designers.py from Admin.Master.
//     Changes to this file are lost when it is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web.Admin
{
    public partial class AdminMaster
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder Head;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder Main;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder Scripts;
    }
}
