//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/admin_designers.py from Application.aspx.
//     Changes to this file are lost when it is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web.Admin
{
    public partial class ApplicationPage
    {
        protected global::System.Web.UI.WebControls.PlaceHolder ErrorBox;

        protected global::System.Web.UI.WebControls.Literal ErrorText;

        protected global::System.Web.UI.WebControls.TextBox Subject;

        protected global::System.Web.UI.WebControls.TextBox Message;

        protected global::System.Web.UI.WebControls.Button SendButton;

        protected global::System.Web.UI.WebControls.DropDownList StatusList;

        protected global::System.Web.UI.WebControls.DropDownList RatingList;

        protected global::System.Web.UI.WebControls.TextBox Notes;

        protected global::System.Web.UI.WebControls.Button SaveButton;

        protected global::System.Web.UI.WebControls.Button DeleteButton;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
