//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/admin_designers.py from Campaign.aspx.
//     Changes to this file are lost when it is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web.Admin
{
    public partial class CampaignPage
    {
        protected global::System.Web.UI.WebControls.PlaceHolder LockedError;

        protected global::System.Web.UI.WebControls.Literal LockedErrorText;

        protected global::System.Web.UI.WebControls.Button SaveButton;

        protected global::System.Web.UI.WebControls.PlaceHolder ErrorBox;

        protected global::System.Web.UI.WebControls.Literal ErrorText;

        protected global::System.Web.UI.WebControls.TextBox Subject;

        protected global::System.Web.UI.WebControls.TextBox Preheader;

        protected global::System.Web.UI.WebControls.TextBox Body;

        protected global::System.Web.UI.WebControls.TextBox TestTo;

        protected global::System.Web.UI.WebControls.Button TestButton;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
