//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/admin_designers.py from ContentEdit.aspx.
//     Changes to this file are lost when it is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web.Admin
{
    public partial class ContentEditPage
    {
        protected global::System.Web.UI.WebControls.Button SaveButton;

        protected global::System.Web.UI.WebControls.PlaceHolder ErrorBox;

        protected global::System.Web.UI.WebControls.Literal ErrorText;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
