//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/admin_designers.py from Email.aspx.
//     Changes to this file are lost when it is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web.Admin
{
    public partial class EmailPage
    {
        protected global::System.Web.UI.WebControls.Button SaveButton;

        protected global::System.Web.UI.WebControls.PlaceHolder ErrorBox;

        protected global::System.Web.UI.WebControls.Literal ErrorText;

        protected global::System.Web.UI.WebControls.PlaceHolder OkBox;

        protected global::System.Web.UI.WebControls.Literal OkText;

        protected global::System.Web.UI.WebControls.TextBox Host;

        protected global::System.Web.UI.WebControls.TextBox Port;

        protected global::System.Web.UI.WebControls.DropDownList Ssl;

        protected global::System.Web.UI.WebControls.TextBox SmtpUser;

        protected global::System.Web.UI.WebControls.TextBox Password;

        protected global::System.Web.UI.WebControls.TextBox FromAddr;

        protected global::System.Web.UI.WebControls.TextBox FromName;

        protected global::System.Web.UI.WebControls.TextBox LeadsTo;

        protected global::System.Web.UI.WebControls.TextBox CareersTo;

        protected global::System.Web.UI.WebControls.TextBox ReplyTo;

        protected global::System.Web.UI.WebControls.CheckBox AutoReply;

        protected global::System.Web.UI.WebControls.TextBox PerMinute;

        protected global::System.Web.UI.WebControls.TextBox PerHour;

        protected global::System.Web.UI.WebControls.TextBox TestTo;

        protected global::System.Web.UI.WebControls.Button TestButton;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
