//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/admin_designers.py from Lead.aspx.
//     Changes to this file are lost when it is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web.Admin
{
    public partial class LeadPage
    {
        protected global::System.Web.UI.WebControls.PlaceHolder ErrorBox;

        protected global::System.Web.UI.WebControls.Literal ErrorText;

        protected global::System.Web.UI.WebControls.TextBox LName;

        protected global::System.Web.UI.WebControls.TextBox LCompany;

        protected global::System.Web.UI.WebControls.TextBox LPhone;

        protected global::System.Web.UI.WebControls.TextBox LEmail;

        protected global::System.Web.UI.WebControls.TextBox LCity;

        protected global::System.Web.UI.WebControls.TextBox LInterest;

        protected global::System.Web.UI.WebControls.TextBox LNeed;

        protected global::System.Web.UI.WebControls.DropDownList LType;

        protected global::System.Web.UI.WebControls.DropDownList LSource;

        protected global::System.Web.UI.WebControls.DropDownList LStatus;

        protected global::System.Web.UI.WebControls.DropDownList LPriority;

        protected global::System.Web.UI.WebControls.TextBox LValue;

        protected global::System.Web.UI.WebControls.DropDownList LOwner;

        protected global::System.Web.UI.WebControls.TextBox LTags;

        protected global::System.Web.UI.WebControls.TextBox LLostReason;

        protected global::System.Web.UI.WebControls.Button SaveButton;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
