//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/admin_designers.py from Login.aspx.
//     Changes to this file are lost when it is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web.Admin
{
    public partial class Login
    {
        protected global::System.Web.UI.WebControls.PlaceHolder ErrorBox;

        protected global::System.Web.UI.WebControls.Literal ErrorText;

        protected global::System.Web.UI.WebControls.TextBox Email;

        protected global::System.Web.UI.WebControls.TextBox Password;

        protected global::System.Web.UI.WebControls.CheckBox Remember;

        protected global::System.Web.UI.WebControls.Button SignInButton;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
