//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/admin_designers.py from Post.aspx.
//     Changes to this file are lost when it is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web.Admin
{
    public partial class PostPage
    {
        protected global::System.Web.UI.WebControls.Button SaveButton;

        protected global::System.Web.UI.WebControls.PlaceHolder ErrorBox;

        protected global::System.Web.UI.WebControls.Literal ErrorText;

        protected global::System.Web.UI.WebControls.TextBox PostTitle;

        protected global::System.Web.UI.WebControls.TextBox Body;

        protected global::System.Web.UI.WebControls.TextBox Excerpt;

        protected global::System.Web.UI.WebControls.DropDownList StatusList;

        protected global::System.Web.UI.WebControls.TextBox Cover;

        protected global::System.Web.UI.WebControls.TextBox Category;

        protected global::System.Web.UI.WebControls.TextBox Author;

        protected global::System.Web.UI.WebControls.TextBox Tags;

        protected global::System.Web.UI.WebControls.TextBox Slug;

        protected global::System.Web.UI.WebControls.TextBox MetaTitle;

        protected global::System.Web.UI.WebControls.TextBox MetaDesc;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
