//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/admin_designers.py from Reports.aspx.
//     Changes to this file are lost when it is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web.Admin
{
    public partial class Reports
    {

    }
}
