//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/admin_designers.py from Subscribers.aspx.
//     Changes to this file are lost when it is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web.Admin
{
    public partial class Subscribers
    {
        protected global::System.Web.UI.WebControls.TextBox NewEmail;

        protected global::System.Web.UI.WebControls.TextBox NewName;

        protected global::System.Web.UI.WebControls.Button AddButton;

        protected global::System.Web.UI.WebControls.TextBox ImportText;

        protected global::System.Web.UI.WebControls.Button ImportButton;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
