//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/admin_designers.py from Team.aspx.
//     Changes to this file are lost when it is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yenetch.Web.Admin
{
    public partial class Team
    {
        protected global::System.Web.UI.WebControls.Panel EditPanel;

        protected global::System.Web.UI.WebControls.TextBox EditName;

        protected global::System.Web.UI.WebControls.DropDownList EditRole;

        protected global::System.Web.UI.WebControls.CheckBox EditActive;

        protected global::System.Web.UI.WebControls.TextBox EditPassword;

        protected global::System.Web.UI.WebControls.Button SaveButton;

        protected global::System.Web.UI.WebControls.Panel AddPanel;

        protected global::System.Web.UI.WebControls.TextBox NewName;

        protected global::System.Web.UI.WebControls.TextBox NewEmail;

        protected global::System.Web.UI.WebControls.DropDownList NewRole;

        protected global::System.Web.UI.WebControls.TextBox NewPassword;

        protected global::System.Web.UI.WebControls.Button AddButton;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
