"""Regenerates the .designer.cs files for the hand-written admin pages (Yenetch.Web/Admin) from their server-control IDs.
Run after adding or renaming a runat="server" control: python3 tools/admin_designers.py"""
import re
from pathlib import Path

ADMIN = Path(__file__).resolve().parent.parent / "Yenetch.Web" / "Admin"
HTML = {"form": "HtmlForm", "head": "HtmlHead"}

for markup in sorted(list(ADMIN.glob("*.aspx")) + list(ADMIN.glob("*.Master"))):
    text = markup.read_text(encoding="utf-8-sig")
    m = re.search(r'Inherits="([\w.]+)\.(\w+)"', text)
    if not m:
        continue
    ns, cls = m.groups()
    fields = []
    for tag, cid in re.findall(r'<asp:(\w+)\b[^>]*?\bID="(\w+)"', text):
        fields.append((f"global::System.Web.UI.WebControls.{tag}", cid))
    for tag, cid in re.findall(r'<(form|head)\b[^>]*?\bid="(\w+)"[^>]*runat="server"', text, re.I):
        fields.append((f"global::System.Web.UI.HtmlControls.{HTML[tag.lower()]}", cid))
    body = "\n\n".join(f"        protected {t} {i};" for t, i in fields)
    out = f"""//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/admin_designers.py from {markup.name}.
//     Changes to this file are lost when it is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace {ns}
{{
    public partial class {cls}
    {{
{body}
    }}
}}
"""
    (markup.parent / (markup.name + ".designer.cs")).write_text(out, encoding="utf-8-sig")
    print(markup.name, len(fields))
